### ISSUE TITLE
Make generated constants extra type-safe by delcaring a new type (e.g. `type foo string`) then...

### ISSUE THREAD

**Issue by 0pdd** [frou/pg2go#3]
The puzzle `0-464a4719` from #0 has to be resolved: 

https://github.com/frou/pg2go/blob/8fffe6e89a1e8af0d58e17e93927b628d8fcbaf1/pg2go.sql#L115-L119

The puzzle was created by Duncan Holm on 18-Aug-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Closing this issue since I'm about to Archive this GitHub repo
